spring.application.name=capstone

#ENV
spring.config.import=file:env.properties

# SERVER CONFIG
server.port=${WEB_SERVER_PORT}

# DB CONFIG
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver=org.postgresql.Driver

# HIBERNATE
spring.jpa.hibernate.ddl-auto=update

#CLOUDINARY CONFIG
cloudinary.key=${CLOUDINARY_API_KEY}
cloudinary.secret=${CLOUDINARY_SECRET}
cloudinary.name=${CLOUDINARY_NAME}

spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=500MB


# MAILGUN
mailgun.apiKey=${MAILGUN_API_KEY}
mailgun.domainName=${MAILGUN_DOMAIN_NAME}

# JWT SECRET
jwt.secret=${JWT_SECRET}

# ADMIN CREDENTIALS
admin.username=${ADMIN_USERNAME}
admin.password=${ADMIN_PASSWORD}
